<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>D:/Program Files/Steam/steamapps/common/Rubinite/Rubinite_Data/Managed/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:/Program Files/Steam/steamapps/common/Rubinite/Rubinite_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>D:/Program Files/Steam/steamapps/common/Rubinite/Rubinite_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:/Program Files/Steam/steamapps/common/Rubinite/Rubinite_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PugTool">
      <HintPath>D:/Program Files/Steam/steamapps/common/Rubinite/Rubinite_Data/Managed/PugTool.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
